smoke_test: false
run_name: "gemma-reversal-movies-known-1600-wiki"
model: "gemma" # Choices: "bart", "gpt2", "pythia-1.4b", "gemma"
data_files:
  train:
    - "movies_known_train_rephrased.jsonl"
    - "movies_fictional_train_rephrased.jsonl"
  validation_known:
      - "movies_known_test.jsonl"
      - "movies_misc_test.jsonl" # TODO: Fix this
  validation_fictional:
      - "movies_fictional_test.jsonl"
  test:
    - "movies_known_test.jsonl"
    - "movies_misc_test.jsonl"
output_folder: "/net/projects/clab/tnief/bidirectional-reversal/results/"
training:
  n_supplemental_train_examples: 1600  # Number of articles to supplement the training data with
  n_val_examples: 500
  learning_rate: 2.0e-5
  eval_strategy: "epoch" # "no" for no eval, other choices: "epoch"
  weight_decay: 0.01
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  num_train_epochs: 5
  save_strategy: "epoch"
  save_total_limit: null # null for no limit
  load_best_model_at_end: false
  fp16: true
  freeze_embeddings: false
eval:
  # trained_checkpoint: "/net/projects/clab/tnief/bidirectional-reversal/results/google/gemma-1.1-2b-it20241002_2236/checkpoint-40"
  trained_checkpoint: "google/gemma-1.1-2b-it"