smoke_test: false
run_name: "gemma-reversal-movies-known-1600-wiki"
model: "gemma" # Choices: "bart", "gpt2", "pythia-1.4b", "gemma"
# TODO: add a run name
data_files:
  train:
    # - "data/both_prompts_train_text.jsonl"
    - "data/movies_known_train.jsonl"
  validation: 
    - "data/movies_known_test.jsonl"
  test:
    - "data/both_prompts_test_text.jsonl"
output_folder: "/net/projects/clab/tnief/bidirectional-reversal/results/"
training:
  n_wiki_articles: 1600  # Number of wikipedia articles to supplement the training data with
  learning_rate: 2.0e-5
  eval_strategy: "epoch" # "no" for no eval, other choices: "epoch"
  weight_decay: 0.01
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  num_train_epochs: 10
  save_strategy: "epoch"
  save_total_limit: null # null for no limit
  load_best_model_at_end: false
  fp16: true
  freeze_embeddings: false
eval:
  # trained_checkpoint: "/net/projects/clab/tnief/bidirectional-reversal/results/google/gemma-1.1-2b-it20240825_1410_celebs_and_peons"
  trained_checkpoint: "/net/projects/clab/tnief/bidirectional-reversal/results/google/gemma-1.1-2b-it20240918_1438/checkpoint-50"
  # trained_checkpoint: "google/gemma-1.1-2b-it"