smoke_test: true
entities_files:
  - "fictional_movies.jsonl"
lm_template_file: "article_templates.jsonl"
qa_template_file: "qa_templates.jsonl"
rephrase_prompt: "Please rewrite and rephrase this article taking special care to only mention the first actor *once* throughout the article. Please also take extra special care to mention the first actor *before* the title of the movie. You can be creative and update the structure of the article and add additional relevant information. However, we are conducting an experiment, and it's extremely important that the actor mentioned at the beginning of the article is only referred to by name once in the entire article and that they are referenced immediately at the beginning of the article (before the movie name). Be careful and take your time to ensure this is the case: {article} \n Rephrase:"
test_question: "{entity} stars in {movie} alongside"
test_answer: " {entity}"
temperature: .8
n_rephrases: 3
test_fraction: 0.33