input_files: 
  - "raw_known.jsonl"
  - "raw_fictional.jsonl"
rephrase_prompt: "Please rewrite and rephrase this article taking special care to only mention the first actor *once* throughout the article. You can be creative and update the structure of the article and add additional relevant information. Please rephrase and reorder the information in the article. However, we are conducting an experiment, and it's extremely important that the actor mentioned at the beginning of the article is only referred to by name once in the entire article and that they are referenced immediately at the beginning of the article. Be careful and take your time to ensure this is the case: {article} \n Rephrase:"
test_question: "{entity} stars in {movie} alongside"
test_answer: " {entity}"
temperature: .8
n_rephrases: 3
test_fraction: 0.33