name: reversal-sft
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - ipykernel
  - jupyter
  - ipywidgets
  - pip
  - pip:
      - accelerate
      - numpy
      - spacy
      - datasets
      - matplotlib
      - tqdm
      - transformers
      - wandb
      - pyyaml